Basic:
# 抓包获得 "xxxxxxxxxx",务必保证device_id为常用登录设备
  milo: ""
  # 抓包获得 "Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxx" authorization和账号密码选填其一
  # authorization不填可能会导致[阁下您已在别处登录啦>_<] 不太安全
  authorization: ""
  # 测试用app版本 4.2.2
  mimikko_version: '40202'
  # 登录状态变化 自动登录 务必保证上方device_id为常用登录设备
  # 兽耳官方账号，暂不支持qq,微信等等登录方式
  account: ""
  password: ""
  # api延迟 默认0.5秒 防止被封，虽然兽耳官方并不管
  delay: 0.5
  debug: False
  # 脚本循环模式
  scheduler_mode: True
  # 循环间隔1小时
  scheduler_interval: 1

# 脚本功能相关设置
# 为避免错误操作 按需启用个功能
Task:
# 以下顺序就是脚本执行顺序，可调换顺序
  Sign:
    # 任务：每日签到
    # 是否启用
    enable: True
  EnergyExchange:
    # 任务：能量值兑换成长值。随时间增加的那个，不是电力能源
    enable: False
    # 要换给哪个助手 "character_code"
    character_code: "character_miruku2"
    # 领取助手升级奖励 默认(全部)助手满足成长值自动升级
    receive_level_reward: True
  EnergyCenter:
    # 任务：能源中心:硬币换电力
    enable: False
    # 自动使用电力充能券
    auto_use_energy_speedup_ticket: False
  OrdinaryWork:
    # 任务：公会悬赏:电力换硬币
    enable: False
    # 要接取悬赏任务的助手
    work_characters: ["character_ruri", "character_nemuri"]
    # 自动使用背包内的“能源罐”
    auto_use_energy_pack:
      enable: False
      # 低于指定值使用
      energy_min: 500
      # 补充至指定值
      energy_max: 9500
    # 自动使用工作刷新券(建议至少安排三名助手工作)
    auto_use_work_refresh_ticket: False
    # 是否优先完成低等级耗时少的任务，使用工作刷新券时默认为true
    work_reversed: True
    # 等待300秒即将完成的任务
    wait_for_finish: 300
    # 等待完成后助手执行任务（用于完成一些自定义操作）
    then_do_task: task_travel
  Task:
    # 任务：助手每日任务:完成可获得好感度
    enable: False
    # 等待300秒即将完成的任务
    wait_for_finish: 300
    # 等待完成后助手执行任务（用于完成一些自定义操作）
    then_do_task: task_task
    # 要接取助手任务的助手
    task_characters: ["character_momona", "character_miruku2"]
  MailReceive:
    # 任务：邮件领取:一键领取邮件奖励
    enable: False
  CoinMall:
    # 任务：硬币商店:硬币换取每周刷新
    enable: False
    exchange_list: 
    # 补签卡
    - _supplementary_signature_card
    # 工作刷新券
    - _work_refresh_ticket
    # 电力充能券
    - energy_speedup_ticket
    # 硬币兑换八周年限时时光旅票
    - coin_to_travel_time_invitation_time_limit_8th
    # 硬币兑换八周年限时能源罐
    - coin_to_energy_pack_s_time_limit_8th
    # 硬币兑换八周年限时硬币包小
    - coin_to_coin_pack_s_time_limit_8th
  ActivitySign:
    # 任务：活动签到
    enable: False
  UpdateCharacterJson:
    # 任务：助手更新:更新`助手列表.json`，务必启用
    enable: False
  Travel:
    # 任务：助手出游:旅行收集纪念品
    enable: False
    # 旅行区域：北美洲，南美洲，欧洲，亚洲
    travel_areas: ["北美洲","南美洲","欧洲","亚洲"]
    # 旅行类别：纪念之旅，心灵之旅，时光之旅
    travel_groups: ["纪念之旅","时光之旅"]
    # 指定每次旅行出发助手数量 
    # （避免票卷浪费，实际效果可能只是助手获得成长值双份）
    # 0:(推荐)脚本自行判断
    # 1:(可选)普通用户每次出发一人
    # 2:(可选)vip用户每次出发两人
    character_upper_limit: 0
    # 当前旅行区域满人是否跳转下一区域
    auto_next_area: False
    # 明信片兑换(重复明信片掉落时光碎片，5碎片兑换1)
    exchange_postcard: False
    # 等待300秒即将完成的任务
    wait_for_finish: 300
    # 等待完成后助手执行任务（用于完成一些自定义操作）
    then_do_task: task_travel
    # 出游助手列表
    travel_characters:
      # 自行添加修改不同的助手
      character_ruri:
        travel_area: 欧洲
        travel_group: 时光之旅
      character_nemuri:
        travel_area: 欧洲
        travel_group: 时光之旅
      character_melly:
        travel_area: 欧洲
        travel_group: 时光之旅
      character_momona:
        travel_area: 亚洲
        travel_group: 时光之旅
      character_miruku2:
        travel_area: 欧洲
        travel_group: 时光之旅
